name: progress_indicators
description: A handful collection of some cool progress indicators and text animators.
version: 0.1.0
author: Asadullah & Waleed
homepage: https://github.com/wal33d006/progress_indicators

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: